### ISSUE TITLE
Publish a release when merging to the main branch

### ISSUE THREAD

**Issue by 5ouma** [5ouma/opml-generator#103]
### ✏️ Describe the feature

Currently, I publish a release manually, but it's better to have an auto-release method.
- Publish a GitHub Releases
- Publish to JSR

### ✔︎ Confirm these checks

- [X] I searched the GitHub [Issues](https://github.com/5ouma/opml-generator/issues) or [Discussions](https://github.com/5ouma/opml-generator/discussions).
- [X] I tried with the latest version.
- [X] I agree to follow the [Code of Conduct](https://github.com/5ouma/opml-generator/blob/main/.github/CODE_OF_CONDUCT.md).
